name: Marcus Berry - Voiceover Artist
favicon: null
layout_spectrum: 0.19360001990571618
typography_spectrum: 0.5308393076993525
title: Site of Marcus Berry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1effd'
    - '#abba99'
    - '#090a0a'
    - '#354c62'
    - '#5b7c96'
  brandStrength: 0.25
  lightness: 0.2762892877217382
  saturation: 0.4005727407056838
  rhythmicContrast: 0.48198709706775844
purpose: []
