name: Marcus Berry - Voiceover Artist
favicon: null
layout_spectrum: 0.19360001990571618
typography_spectrum: 0.5308393076993525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.056991137098520994
  lightness: 0.2762892877217382
  saturation: 0.4005727407056838
  rhythmicContrast: 0.48198709706775844
purpose: []
